### ISSUE TITLE
Licence type

### ISSUE THREAD

**Issue by Josverl** [BradenM/micropy-stubs#1]
Hi Braden,

would you consider changing the license type to MIT ?

currently the GPL license you have added on top of the MIT work I have done , prevents me from using your work. which is a shame

/jos

**Comment by BradenM** [comment]
Absolutely! To be completely honest, I'm not sure why I put a GPL on this repo haha, it doesn't really fit well. 

Probably just did a copy & paste and forgot about it.

**Comment by BradenM** [comment]
Whoops, didn't mean to reopen.

When I get back to a desktop today I will cleanup some of the code in here and add some better documentation.
