### ISSUE TITLE
ESP32 v1.13 stubs?

### ISSUE THREAD

**Issue by bjonesrock** [BradenM/micropy-stubs#13]
Hello! Love your project, I'm working on a project that requires micropython v1.13 on the ESP32

Right now I'm using the stubs for version 1.12 but it would be awesome if Visual Studio Code wasn't giving me fake errors. 

I noticed that Josverl has the stubs for the ESP32 v1.13:
https://github.com/Josverl/micropython-stubs/blob/master/firmwares.md

Would it be possible to update your list of stubs to include the latest version of micropython for the ESP32?

Thanks!!!!
-Ben

**Comment by bjonesrock** [comment]
So I'm an idiot and I posted this to the wrong repository, I meant to put it on the micropy cli repo. Anyway I just followed the instructions and manually got the stubs for the ESP32 v1.13 working.

**Comment by BradenM** [comment]
@bjonesrock, well actually this issue would be more appropriate here than the main repo :smile: Not that it matters that much anyways.

Glad you were able to manually install the stubs. I need to get with @Josverl at some point to discuss potentially opening his repository of stubs up to micropy-cli.

**Comment by bjonesrock** [comment]
That would be great! It's nice having the latest stubs for the ESP32 working in visual studio code, and micropy-cli makes it so easy to set things up.
