### ISSUE TITLE
Atleast manually run the stubs update. The cron job has not been working for 3 years.

### ISSUE THREAD

**Issue by MinecraftPublisher** [BradenM/micropy-stubs#21]
TItle

**Comment by BradenM** [comment]
@MinecraftPublisher This repository is mostly deprecated (primarily due to lack of external contributions) in favor of micropython-stubs.

See: https://github.com/BradenM/micropy-cli/issues/299 for more details

As of now, you can install the stubs from micropython-stubs directly from micropy-cli.

**Comment by MinecraftPublisher** [comment]
Well then thanks!
